# Generated by Django 5.0.6 on 2024-06-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('menu', models.TextField(verbose_name='Items')),
                ('full_details', models.TextField()),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City')),
                ('user_rating', models.CharField(default='None', max_length=255, verbose_name='User rating')),
                ('votes', models.IntegerField(default=0)),
                ('avg_rating', models.FloatField(default=0)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Item Name')),
                ('price', models.FloatField()),
                ('created', models.DateField(auto_now_add=True)),
                ('res', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.restaurant')),
            ],
        ),
    ]
