# Generated by Django 5.0.6 on 2024-06-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='lat_long',
            field=models.CharField(default='', max_length=255, verbose_name='Lat-Long'),
        ),
    ]
